### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by kroyee** [kroyee/SpeedBlocks#1]
- [x] Make code generic for Windows/Mac/Linux
- [ ] Implement ranking for players with "Hero rank"
- [ ] Set up webhost for the forum/ranking

__Make the code generic__
With regards to MacOS finding the right path to resources a resourcePath() function has been implemented to deal with it. Compiling under Windows or Linux gives a NULL function to replace it.
Added alternative to to_string() and stoi() for MingW users. Compiling with other compiler uses standard functions.
This is considered complete as of now.

__Implement ranking for players with "Hero rank"__
Ranking system is divided in 2 part, first you rank up from 25 to 1 and last Hero Rank. As of now that part works. To be added is ELO ranking between players who has reached Hero Rank.

__Set up webhost for the forum/ranking__
A webhost that can host the forum and the ranking stats. Forum to be used is [SMF](http://www.simplemachines.org/). Ideally the host will also have the game-server running on it.

**Comment by zDEFz** [comment]
Add proper DAS - like in jstris.
I misdrop often and i don't know why.

jezevec10 is developer of jstris.
http://imgur.com/a/GZgbC

**Comment by kroyee** [comment]
Not sure what proper DAS means. Do you have some info on the mechanics behind it?

**Comment by zDEFz** [comment]
No i don't.
I just have issues playing properly.

Compared it to cultris ii and jstris and i saw that i can not stay in flow. It's like 1 block to far / to less.

**Comment by zDEFz** [comment]
(Could we have assignable labels like I did with [] somehow?)

https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/

[UX] 
[FN]
[TN]
[GUI]

UX = User Experience
FN = Functional
TN = Technical
GUI = Graphical User Interface

**Comment by ghost** [comment]
Hello super,

I think that the **ghost piece** is **too dark** compared to the **locked down pieces** when close to one another. maybe if you add a faint **outlin**e or **glow** it could make the ghost piece more **visible**.

Thanks, 

Explo.

**Comment by kroyee** [comment]
@Expl0sive You could try and experiment with the colors and alpha values. In textures.cpp you can see all the colors defined as sf::Color(R,G,B, Alpha), first 8 ones are for normal blocks, the seconds set of 8 are for ghost pieces.

**Comment by Noir-** [comment]
Whats the exact reason for this list? Is this the first "milestone"? Then we should actually create one and assign this issue to it! Even better would be when all things mentioned here are separated into their own issue so that they can be more easily discussed and closed when they are implemented or dismissed.

**Comment by kroyee** [comment]
Sounds like a much better approach. But yeah, it was kind of a milestone i guess.
